steps:
# This step runs the unit tests on the app
- name: 'python:3.7-slim'
  id: Test
  entrypoint: /bin/sh
  args:
  - -c
  - 'pip install flask && python test_app.py -v'

# This step builds the container image.
- name: 'gcr.io/cloud-builders/docker-nginx'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/docker-nginx:$SHORT_SHA'
  - '.'

# This step pushes the image to Container Registry
# The PROJECT_ID and SHORT_SHA variables are automatically
# replaced by Cloud Build.
- name: 'gcr.io/cloud-builders/docker-nginx'
  id: Push
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/docker-nginx:$SHORT_SHA'
# [END cloudbuild]


# This step deploys the new version of our container image
# in the nginx-cloudbuild App Engine.

steps:
- name: 'gcr.io/cloud-builders/docker-nginx'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/docker-nginx:$SHORT_SHA' ]
images:
- 'gcr.io/$PROJECT_ID/docker-nginx:$SHORT_SHA'